window.School = (() => {
const key='chom-school-prototype-v1';
const subjects=[{id:'maths',name:'Mathematics',short:'Ma',teacher:'Mr Dlamini',color:'#eef3ff',ink:'#2860f5',topic:'Functions & graphs'},{id:'science',name:'Physical Sciences',short:'Ps',teacher:'Ms Jacobs',color:'#fff2e9',ink:'#a65c2c',topic:'Waves, sound & light'},{id:'english',name:'English',short:'En',teacher:'Ms Adams',color:'#f0edf9',ink:'#746294',topic:'Poetry & literature'}];
const seed={tasks:[{id:'t1',title:'Complete the functions worksheet',subject:'maths',className:'10B',date:'2026-10-09',body:'Complete questions 1–8. Show your working.',done:false},{id:'t2',title:'Read the next two chapters',subject:'english',className:'10B',date:'2026-10-12',body:'Make notes on the main character’s decisions.',done:false}],assignments:[{id:'a1',title:'Quadratic functions investigation',subject:'maths',className:'10B',date:'2026-10-14',body:'Explore how a, b and c change the shape of a parabola. Draw and label three examples, then explain your findings.',marks:'50',status:'Published',submitted:24},{id:'a2',title:'Waves in everyday life',subject:'science',className:'10B',date:'2026-10-16',body:'Choose an example of waves in everyday life and explain its properties.',marks:'30',status:'Published',submitted:12}],files:[{id:'f1',title:'Functions & graphs — study notes',subject:'maths',className:'10B',filename:'functions-study-notes.txt',sample:true,body:'FUNCTIONS & GRAPHS\n\nA function maps each input to exactly one output.\nA straight line has the form y = mx + c.\nA quadratic function has the form y = ax² + bx + c.\n\nPractice: sketch y = x², y = 2x² and y = x² + 3. Describe how each graph changes.',size:'Study notes'},{id:'f2',title:'Revision practice: functions',subject:'maths',className:'10B',filename:'revision-practice.txt',sample:true,body:'REVISION PRACTICE\n\n1. Find the gradient of y = 3x + 2.\n2. Find the roots of y = x² - 4.\n3. Explain the effect of c in y = x² + c.',size:'Worksheet'},{id:'f3',title:'Introduction to waves',subject:'science',className:'10B',filename:'waves-notes.txt',sample:true,body:'WAVES\n\nWavelength: distance between two successive crests.\nFrequency: number of cycles per second.\nWave speed = frequency × wavelength.',size:'Study notes'},{id:'f4',title:'Poetry reading guide',subject:'english',className:'10B',filename:'poetry-guide.txt',sample:true,body:'READING POETRY\n\nRead once for meaning, then again for sound.\nIdentify the speaker, tone and imagery.\nSupport your interpretation with evidence from the poem.',size:'Reading'}],events:[{id:'e1',title:'Grade 10B · Functions revision',subject:'maths',className:'10B',date:'2026-10-08',time:'09:40',body:'Room 12'},{id:'e2',title:'Science practical',subject:'science',className:'10B',date:'2026-10-12',time:'11:30',body:'Science lab'},{id:'e3',title:'Mathematics assessment',subject:'maths',className:'10B',date:'2026-10-14',time:'08:30',body:'Bring your calculator.'}]};
let data;try{data=JSON.parse(localStorage.getItem(key))}catch{}if(!data||!Array.isArray(data.tasks))data=structuredClone(seed);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem(key,JSON.stringify(data));return true}catch{return false}}
function db(){return new Promise((ok,no)=>{let r=indexedDB.open('chom-prototype-files',1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function put(id,file){const d=await db();return new Promise((ok,no)=>{const t=d.transaction('files','readwrite');t.objectStore('files').put(file,id);t.oncomplete=()=>{d.close();ok()};t.onerror=()=>no(t.error)})}
async function download(id){let f=data.files.find(x=>x.id===id);if(!f)return;let blob;if(f.sample)blob=new Blob([f.body],{type:'text/plain'});else{const d=await db();blob=await new Promise((ok,no)=>{const r=d.transaction('files').objectStore('files').get(id);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});d.close()}if(!blob){alert('This file is not available in this browser. Upload it again in the teacher preview.');return}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=f.filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
const subject=id=>subjects.find(x=>x.id===id)||subjects[0];const date=s=>new Date(s+'T12:00:00').toLocaleDateString('en-ZA',{day:'numeric',month:'short'});
function student(){const id=new URLSearchParams(location.hash.split('?')[1]||'').get('subject');const s=subjects.find(x=>x.id===id);const pill='<span class="subject-preview-note">Class 10B · Browser-only preview</span>';if(!s)return `<header class="view-header"><div><h1>My subjects</h1><p>Your class material, all in one place.</p></div>${pill}</header><div class="subject-grid">${subjects.map(s=>`<a class="subject-card" href="#subjects?subject=${s.id}"><span class="subject-symbol" style="background:${s.color};color:${s.ink}">${s.short}</span><h2>${s.name}</h2><p>${s.teacher} · Grade 10B</p><div class="subject-card-bottom">${data.files.filter(f=>f.subject===s.id&&f.className==='10B').length} resources <span>Open subject</span></div></a>`).join('')}</div><div class="notice">Sample learning material. Teacher changes appear here on the same URL and browser. Separate deployments do not sync.</div>`;
const own=x=>x.subject===id&&x.className==='10B';return `<a class="subject-back" href="#subjects">All my subjects</a><header class="view-header"><div><h1>${s.name}</h1><p>${s.teacher} · Grade 10B · ${s.topic}</p></div>${pill}</header><section class="panel subject-section"><h2>Learning material</h2>${data.files.filter(own).map(f=>`<div class="subject-resource"><div><strong>${esc(f.title)}</strong><p>${esc(f.filename)} · ${esc(f.size)}</p></div><button class="button secondary" data-school-download="${esc(f.id)}">Download</button></div>`).join('')||'<p>No material yet.</p>'}</section><section class="panel subject-section"><h2>Assignments</h2>${data.assignments.filter(x=>own(x)&&x.status==='Published').map(a=>`<details class="subject-resource-detail"><summary><strong>${esc(a.title)}</strong><span>Due ${date(a.date)} · ${esc(a.marks)} marks</span></summary><p>${esc(a.body)}</p></details>`).join('')||'<p>No assignments yet.</p>'}</section><section class="panel subject-section"><h2>Class tasks</h2>${data.tasks.filter(own).map(t=>`<div class="subject-resource"><label><input type="checkbox" data-school-task="${esc(t.id)}" ${t.done?'checked':''}> <strong>${esc(t.title)}</strong><p>${esc(t.body)}</p></label><span>Due ${date(t.date)}</span></div>`).join('')||'<p>No tasks yet.</p>'}</section><section class="panel subject-section"><h2>Upcoming events</h2>${data.events.filter(own).map(e=>`<div class="subject-resource"><div><strong>${esc(e.title)}</strong><p>${esc(e.body)}</p></div><span>${date(e.date)} · ${esc(e.time)}</span></div>`).join('')||'<p>No events yet.</p>'}</section>`}
document.addEventListener('click',e=>{const b=e.target.closest('[data-school-download]');if(b)download(b.dataset.schoolDownload).catch(()=>alert('The download could not be opened. Please try again.'))});
document.addEventListener('change',e=>{if(e.target.matches('[data-school-task]')){data.tasks.find(t=>t.id===e.target.dataset.schoolTask).done=e.target.checked;save()}});
return {data,subjects,subject,date,esc,save,put,download,student};})();
